### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by m10x** [tls-attacker/TLS-Scanner#97]
When scanning certain domains the TLS Scanner often (but not always) crashes because of the following exception

![image](https://github.com/user-attachments/assets/713b3884-2ae9-4f3f-913f-276786265769)

**Comment by ic0ns** [comment]
Looks like the issue is coming from here:

https://github.com/tls-attacker/TLS-Scanner/blob/7fd1969f398e2b41f8116e8062d3e198658eed44/TLS-Server-Scanner/src/main/java/de/rub/nds/tlsscanner/serverscanner/probe/CertificateTransparencyProbe.java#L221C81-L221C84

The core of the issue is that TLS-Scanner was unable to read the certificate chain of the domain which then causes ArrayIndexOutOfBounds exception when trying to to get the leaf certificate. As a workaround you can disable the CertificateTransparencyProbe here by commenting it out:
https://github.com/tls-attacker/TLS-Scanner/blob/7fd1969f398e2b41f8116e8062d3e198658eed44/TLS-Server-Scanner/src/main/java/de/rub/nds/tlsscanner/serverscanner/execution/TlsServerScanner.java#L167

**Comment by JonSnowWhite** [comment]
The CertificateTransparancyProbe was removed in later versions of TLS-Scanner.
